In [1]:
from bs4 import BeautifulSoup
from pycookiecheat import chrome_cookies
import pandas as pd
import requests

ModuleNotFoundError: No module named 'bs4'

In [2]:
import sys
sys.path
sys.path.append('/usr/local/lib/python3.7/site-packages')
sys.path

['/Users/Dimitris/Google Drive/Big Data Content Analytics Project/dev',
 '/Library/Frameworks/Python.framework/Versions/3.7/lib/python37.zip',
 '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7',
 '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload',
 '',
 '/Users/Dimitris/Library/Python/3.7/lib/python/site-packages',
 '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages',
 '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/extensions',
 '/Users/Dimitris/.ipython',
 '/usr/local/lib/python3.7/site-packages']

In [ ]:
page = 1
url = "https://www.bloomberg.com/search?query=Facebook&startTime=2017-12-01T00:00:00.000Z&endTime=2018-07-31T00:00:00.00Z&page=" + page

# Uses Chrome's default cookies filepath by default
cookies = chrome_cookies(url)
# print(cookies)

postData = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:67.0) Gecko/20100101 Firefox/67.0"
}

r = requests.get(url, cookies=cookies, data=postData)
soup = BeautifulSoup(r.content, "html")
links = soup.find_all("div", attrs={"class":"search-result"})
#print(links)

In [55]:
# Uses Chrome's default cookies filepath by default
url = 'https://www.bloomberg.com/search?query=Facebook&startTime=2015-01-01T00:00:00.000Z&endTime=2017-12-31T00:00:00.00Z&page=1'
cookies = chrome_cookies(url)

articles_links = []

for i in range(0,200):
    page = i #+ 10
    #url = "https://www.bloomberg.com/search?query=Facebook" + \
    #    "&startTime=2017-12-01T00:00:00.000Z" + \
    #    "&endTime=2018-07-31T00:00:00.00Z" + \
    #    "&page=" + str(page)
    #url = "https://www.bloomberg.com/search?query=Facebook" + \
    #    "&startTime=2015-01-01T00:00:00.000Z" + \
    #    "&endTime=2017-12-31T00:00:00.00Z" + \
    #    "&page=" + str(page) 
    #url = "https://www.bloomberg.com/search?query=Facebook" + \
    #    "&startTime=2013-01-01T00:00:00.000Z" + \
    #    "&endTime=2015-12-31T00:00:00.00Z" + \
    #    "&page=" + str(page) 
    url = "https://www.bloomberg.com/search?query=Facebook" + \
        "&startTime=2010-01-01T00:00:00.000Z" + \
        "&endTime=2012-12-31T00:00:00.00Z" + \
        "&page=" + str(page) 
    
    
    postData = {
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:67.0) Gecko/20100101 Firefox/67.0"
    }

    r = requests.get(url, cookies=cookies, data=postData)
    soup = BeautifulSoup(r.content, "html")
    links = soup.find_all("div", attrs={"class":"search-result"})
    print(str(len(links)) + ' ' + str(page))
    articles_links.append(links)
    #print(links)

0 0
10 1
10 2
10 3
10 4
10 5
10 6
10 7
10 8
10 9
10 10
10 11
10 12
10 13
10 14
10 15
10 16
10 17
10 18
10 19
10 20
10 21
10 22
10 23
10 24
10 25
10 26
10 27
10 28
10 29
10 30
10 31
10 32
10 33
10 34
10 35
10 36
10 37
10 38
10 39
10 40
10 41
10 42
10 43
10 44
10 45
10 46
10 47
10 48
10 49
10 50
10 51
10 52
10 53
10 54
10 55
10 56
10 57
10 58
10 59
10 60
10 61
10 62
10 63
10 64
10 65
10 66
10 67
10 68
10 69
10 70
10 71
10 72
10 73
10 74
10 75
10 76
10 77
10 78
10 79
10 80
10 81
10 82
10 83
10 84
10 85
10 86
10 87
10 88
10 89
10 90
10 91
10 92
10 93
10 94
10 95
10 96
10 97
10 98
10 99
10 100
10 101
10 102
10 103
10 104
10 105
10 106
10 107
10 108
10 109
10 110
10 111
10 112
10 113
10 114
10 115
10 116
10 117
10 118
10 119
10 120
10 121
10 122
10 123
10 124
10 125
10 126
10 127
10 128
10 129
10 130
10 131
10 132
10 133
10 134
10 135
10 136
10 137
10 138
10 139
10 140
10 141
10 142
10 143
10 144
10 145
10 146
10 147
10 148
10 149
10 150
10 151
10 152
10 153
10 154
10 155
10 156
10 157
10 158
10 159
10 160
10 161
10 162
10 163
10 164
10 165
10 166
10 167
10 168
10 169
10 170
10 171
10 172
10 173
10 174
10 175
10 176
10 177
10 178
10 179
10 180
10 181
10 182
10 183
10 184
10 185
10 186
10 187
10 188
10 189
10 190
10 191
10 192
10 193
10 194
10 195
10 196
10 197
10 198
10 199

In [56]:
len(articles_links)

200

In [57]:
#len(articles_links)
flat_list = [item for sublist in articles_links for item in sublist]

In [58]:
len(flat_list)

1990

In [90]:
manyindf = df

In [92]:
manyindf.head()

,Timestamp,Metadata,Headline,URL,ShortDesc
0,2018-04-06T11:44:24+00:00,,"Bloomberg - Daybreak: April 6, 2018 - Hour 1 ...",https://www.bloomberg.com/news/audio/2018-04-0...,Director/Chief Economist Wells Fargo Securiti...
1,2018-04-06T06:30:27+00:00,,Brexit Bulletin: The To-Do List,https://www.bloomberg.com/news/articles/2018-0...,"in the run-up to Brexit,” the newspaper says...."
2,2018-04-05T22:08:50+00:00,technology,CalSTRS Will Engage With Facebook in Midst of...,https://www.bloomberg.com/news/articles/2018-0...,disgruntled Facebook users by removing his pe...
3,2018-04-05T20:36:33+00:00,,"Bloomberg Baystate Business: Facebook, Tariff...",https://www.bloomberg.com/news/audio/2018-04-0...,Bloomberg Television of Emily Chang’s intervi...
4,2018-04-05T19:30:59+00:00,technology,Sheryl Sandberg Says She 'Believes Deeply' in...,https://www.bloomberg.com/news/videos/2018-04-...,...

In [59]:
import pandas as pd

df = pd.DataFrame(columns=["Timestamp", "Metadata", "Headline", "URL", "ShortDesc"])

for link in flat_list:
    timestamp = link.find("time", attrs={"class":"published-at"})['datetime']
    metadata = link.find("a", attrs={"class":"metadata-site"}).text if link.find("a", attrs={"class":"metadata-site"}) else ''
    headline = link.find('h1', attrs={"class":"search-result-story__headline"}).text
    url = link.findAll("a")[-1]['href']
    shortDesc = link.find("div", attrs={"class":"search-result-story__body"}).text
    df = df.append({'Timestamp': timestamp,
                    'Metadata':metadata,
                   'Headline': headline,
                    'URL': url,
                    'ShortDesc': shortDesc
                   }, ignore_index=True)

df

,Timestamp,Metadata,Headline,URL,ShortDesc
0,2012-04-10T18:13:19+00:00,,Top Trending Searches on Google for April 10,https://www.bloomberg.com/news/articles/2012-0...,======================================...
1,2012-07-05T18:09:36+00:00,,Sony Ups ‘Spider-Man’ View After $59 Million ...,https://www.bloomberg.com/news/articles/2012-0...,"has a new cast, with Andrew Garfield replacin..."
2,2012-07-05T04:00:01+00:00,,‘Spider-Man’ Spins $35 Million Opening Ahead ...,https://www.bloomberg.com/news/articles/2012-0...,"This version has a new cast, with U.K.-raised..."
3,2010-10-18T13:47:34+00:00,,‘Jackass 3-D’ Is Top Film With $50 Million in...,https://www.bloomberg.com/news/articles/2010-1...,” Sony Corp.’s drama about the founding of Fa...
4,2010-10-11T21:33:02+00:00,,Sony’s ‘Social Network’ Top Film With $15.5 M...,https://www.bloomberg.com/news/articles/2010-1...,Network” follows critical acclaim for the mov...
5,2010-10-03T19:08:05+00:00,,Sony’s ‘The Social Network’ Top Movie With $2...,https://www.bloomberg.com/news/articles/2010-1...,"“The Social Network,” a movie chronicling the..."
6,2012-03-13T18:38:23+00:00,markets,Goldman Sachs Hires Ex-Treasury Aide Siewert ...,https://www.bloomberg.com/news/articles/2012-0...,"firms, and working for special interest group..."
7,2012-03-13T13:32:34+00:00,,Patent Wars Hit Social Media as Yahoo Sues Fa...,https://www.bloomberg.com/news/articles/2012-0...,Bloomberg's Cris Valerio reports that Faceboo...
8,2012-03-23T01:12:18+00:00,,Should Apple Buy Twitter?,https://www.bloomberg.com/news/articles/2012-0...,that the company would ever strike a similar ...
9,2012-03-22T23:37:21+00:00,technology,‘Angry Birds’ Space Edition Skips Windows Pho...,https://www.bloomberg.com/news/articles/2012-0...,store in 2010 before being rolled out for And...
10,2012-03-22T15:49:43+00:00,,Mali Army Officers Say Toure Government Has B...,https://www.bloomberg.com/news/articles/2012-0...,"Wetangula, who is currently in Bamako to atte..."
11,2012-03-08T01:19:49+00:00,,Joining the (Cash) Mob to Help Main Street,https://www.bloomberg.com/news/articles/2012-0...,seized that message and borrowed from flash m...
12,2012-03-09T03:27:40+00:00,,Kraft's Planters Heads for the Peanut Butter ...,https://www.bloomberg.com/news/articles/2012-0...,While Planters’ brand recognition and Peanu...
13,2012-03-08T22:00:00+00:00,technology,Andreessen Horowitz Invests in Software Start...,https://www.bloomberg.com/news/articles/2012-0...,"NationBuilder, the Los Angeles-based company ..."
14,2012-03-08T07:44:38+00:00,technology,Samsung Proves Jobs Wrong With Pen-Tab: Rich ...,https://www.bloomberg.com/news/articles/2012-0...,"tapping the glass, after which I could add ha..."
15,2012-03-01T13:50:00+00:00,technology,Deutsche Bank Tweets on IPOs as Street Warms ...,https://www.bloomberg.com/news/articles/2012-0...,"Barclays Plc, and Bank of America Corp., the ..."
16,2012-03-01T00:33:55+00:00,,How Three Germans Are Cloning the Web,https://www.bloomberg.com/news/articles/2012-0...,"social network, the Samwers invested in Faceb..."
17,2012-03-06T16:54:32+00:00,technology,Facebook Loses German Ruling Over Friend Find...,https://www.bloomberg.com/news/articles/2012-0...,Facebook Inc. lost a ruling in Germany over u...
18,2012-03-05T21:18:09+00:00,technology,Yahoo Said to Consider Job Cuts as CEO Aims f...,https://www.bloomberg.com/news/articles/2012-0...,CEO in September. Online advertisers have inc...
19,2012-03-02T22:21:41+00:00,technology,Yelp Surges in Debut After IPO Raises More Th...,https://www.bloomberg.com/news/articles/2012-0...,reach profitability while contending with com...
20,2012-04-02T20:39:27+00:00,,Playing Office: Actors as Business Leaders,https://www.bloomberg.com/news/photo-essays/20...,Oscar nomination for his portrayal of a darkl...
21,2012-04-03T22:51:47+00:00,technology,Facebook Fires Back at Yahoo,https://www.bloomberg.com/news/articles/2012-0...,"Facebook Inc., which operates the world’s big..."
22,2012-04-03T12:55:23+00:00,technology,Can Charlie Sheen Sell a Fiat?,https://www.bloomberg.com/news/articles/2012-0...,Schatzker reports that major car companies ar...
23,2012-03-30T00:50:02+00:00,,Social Networking Takes Center Stage at P&G,https://www.bloomberg.com/news/articles/2012-0...,to lure potential customers before their eati...
24,2011-12-11T15:04:22+00:00,technology,"Israel’s Babylon Says Arab World, Brazil to B...",https://www.bloomberg.com/news/articles/2011-1...,a blogger who founded a youth movement on Fac...
25,2011-12-08T04:55:42+00:00,,"If We Are All Journalists, Should We All Be P...",https://www.bloomberg.com/news/articles/2011-1...,rising tide. More from GigaOM:...
26,2012-01-06T09:21:32+00:00,,Police to Allow Pro-Anwar Rally During Malays...,https://www.bloomberg.com/news/articles/2012-0...,"public order and safety, the city’s Police Ch..."
27,2012-01-05T05:01:01+00:00,,Yahoo Stakes Its Future on Engineer Unproven ...,https://www.bloomberg.com/news/articles/2012-0...,"Internet-search provider, now an also-ran in ..."
28,2012-01-03T00:00:01+00:00,technology,"Mastodon Battles Death Fears, Hugs Dinosaur o...",https://www.bloomberg.com/news/articles/2012-0...,"Mastodon’s lightening up, they posed next to ..."
29,2011-11-09T01:00:15+00:00,,Complicating Twitter and Journalism,https://www.bloomberg.com/news/articles/2011-1...,facts of a story whose reporter happens to ha...
...,...,...,...,...,...
1960,2012-10-22T14:06:01+00:00,technology,Facebook Gains as Tool for Terrorists Seeking...,https://www.bloomberg.com/news/articles/2012-1...,irregardless of borders.” Spokespeople at Fac...
1961,2012-10-19T17:13:58+00:00,,Roger Martin Steps Down as Rotman’s Dean,https://www.bloomberg.com/news/articles/2012-1...,” Join the discussion on the Bloomberg ...
1962,2012-10-19T00:41:25+00:00,businessweek,When the Boss Is on Team Romney,https://www.bloomberg.com/news/articles/2012-1...,"political opponent, including “liking” him on..."
1963,2012-10-18T22:46:29+00:00,,Addepar's Software for the Super-Rich,https://www.bloomberg.com/news/articles/2012-1...,"practical experience in finance, but found hi..."
1964,2012-10-18T17:11:31+00:00,,Google Edges Facebook in Software Engineer Pa...,https://www.bloomberg.com/news/articles/2012-1...,"engineers an average base salary of $128,336...."
1965,2012-05-14T20:56:45+00:00,technology,Facebook Said Set to Finish Taking IPO Orders...,https://www.bloomberg.com/news/articles/2012-0...,Facebook Inc. plans to stop taking orders tom...
1966,2012-05-16T04:01:00+00:00,technology,"Spammers Invade Pinterest-Era Social Media, A...",https://www.bloomberg.com/news/articles/2012-0...,"‘Con Artists’“For an average Facebook scam,..."
1967,2012-05-15T19:15:07+00:00,,Can Yahoo Become a Modern Media Company?,https://www.bloomberg.com/news/articles/2012-0...,behavior. Just how valuable that is for Faceb...
1968,2012-05-15T11:55:00+00:00,technology,Top Headlines: Former Murdoch Aide Brooks Cha...,https://www.bloomberg.com/news/articles/2012-0...,Bloomberg's Scarlet Fu reports on the morning...
1969,2012-05-15T02:56:04+00:00,technology,"Mixi Rises on Report DeNA, Gree May Bid on St...",https://www.bloomberg.com/news/articles/2012-0...,"Web in Japan, has lost about 92 percent of it..."
1970,2012-11-17T05:00:01+00:00,technology,Dow Falls for Fourth Week Amid Federal Budget...,https://www.bloomberg.com/news/articles/2012-1...,analysts’ estimates as price reductions helpe...
1971,2012-11-16T17:38:57+00:00,,"Israel, Twitter, and the Line Between Free Sp...",https://www.bloomberg.com/news/articles/2012-1...,down—leaving open the question of what Facebo...
1972,2012-11-15T23:11:43+00:00,,The Hackers of Damascus,https://www.bloomberg.com/news/articles/2012-1...,struggle for the future of the country has al...
1973,2012-11-15T03:00:00+00:00,markets,Israel Wages Twitter War With Hamas Over #Gaz...,https://www.bloomberg.com/news/articles/2012-1...,organization by the U.S. and Israel. Social n...
1974,2012-11-14T23:14:44+00:00,,"Tiger Global Bought Yahoo, Burger King, Faceb...",https://www.bloomberg.com/news/articles/2012-1...,an early investor in Facebook and Russian Web...
1975,2012-11-14T05:00:01+00:00,technology,Failed Facebook Stock Deal Brokered From Jail...,https://www.bloomberg.com/news/articles/2012-1...,"Weiner, Stratos’s lawyer. “I had intimate con..."
1976,2012-08-15T20:40:22+00:00,technology,Facebook Director Thiel Gets More Flexibility...,https://www.bloomberg.com/news/articles/2012-0...,"Cain, spokesman for Thiel, declined to commen..."
1977,2012-08-14T21:40:04+00:00,,When Founders Hire a Boss and Give Up Control,https://www.bloomberg.com/news/articles/2012-0...,"to get two or three testimonials, but [eMeals..."
1978,2012-08-14T21:00:31+00:00,view,An $8.5 Billion IPO Looks Like the Next Faceb...,https://www.bloombergview.com/articles/2012-08...,whether the market will give JAL the Facebook...
1979,2012-08-14T20:16:05+00:00,technology,The Top Ten Stocks for Aug. 14,https://www.bloomberg.com/news/articles/2012-0...,"Regan, Matt Miller and Adam Johnson report on..."
1980,2012-12-11T16:56:31+00:00,,The Pope's Social Media Guru On @Pontifex's F...,https://www.bloomberg.com/news/articles/2012-1...,Dalai Lama didn’t follow anyone. How do you d...
1981,2012-12-10T19:46:31+00:00,businessweek,The Syrian Regime's Survival Strategy: Shut D...,https://www.bloomberg.com/news/articles/2012-1...,When the Internet went dark in Syria last mon...
1982,2012-12-10T15:36:36+00:00,,Trained Incapacity: The Rise of Specialized M...,https://www.bloomberg.com/news/articles/2012-1...,Join the discussion on the Bloomberg B...
1983,2012-11-29T21:11:32+00:00,,"Software Bug Made Swedish Exchange Go Bork, B...",https://www.bloomberg.com/news/articles/2012-1...,Capital’s accidental stock-buying binge; and ...
1984,2012-11-28T14:41:45+00:00,technology,Zynga of Russia That Doesn’t Want to Be Zynga...,https://www.bloomberg.com/news/articles/2012-1...,” Russia’s ZyngaWhile comparisons with Zynga...
1985,2012-11-28T09:59:51+00:00,,Lee Rues Singapore as Retirement Home Unless ...,https://www.bloomberg.com/news/articles/2012-1...,in the World Bank’s ranking of business condi...
1986,2012-06-27T14:59:40+00:00,,How I Got Here: Salesforce Rypple's Daniel De...,https://www.bloomberg.com/news/articles/2012-0...,and raised some money right before the crash ...
1987,2012-06-25T10:28:03+00:00,technology,Publicis Hit by Stagnant China Ads as Europe ...,https://www.bloomberg.com/news/articles/2012-0...,and The Creative Factory in Russia. Advertisi...
1988,2012-06-21T23:03:24+00:00,,Facebook IPO Prompts Call by Issa for SEC Rev...,https://www.bloomberg.com/news/articles/2012-0...,"Morgan Stanley, Facebook’s lead underwriter, ..."
1989,2012-06-21T23:00:43+00:00,,Briefs,https://www.bloomberg.com/news/articles/2012-0...,Facebook: New ads know where you are Fa...

In [60]:
#df.to_csv('/Users/Dimitris/Desktop/missing20_75to95_pages.csv')

df.to_csv('/Users/Dimitris/Desktop/headlines_Jan2010_Dec2012_200pages_20190624.csv')

In [62]:
f1 = pd.read_csv('/Users/Dimitris/Desktop/tenpages.csv')
f2 = pd.read_csv('/Users/Dimitris/Desktop/tenTO100pages.csv')
f3 = pd.read_csv('/Users/Dimitris/Desktop/missing20_75to95_pages.csv')
f4 = pd.read_csv('/Users/Dimitris/Desktop/headlines_Jan2015_Dec2017_100pages_20190624.csv')
f5 = pd.read_csv('/Users/Dimitris/Desktop/headlines_Jan2015_Dec2017_100to200pages_20190624.csv')
f6 = pd.read_csv('/Users/Dimitris/Desktop/headlines_Jan2013_Dec2015_159pages_20190624.csv')
f7 = pd.read_csv('/Users/Dimitris/Desktop/headlines_Jan2013_Dec2015_160to200pages_20190624.csv')
f8 = pd.read_csv('/Users/Dimitris/Desktop/headlines_Jan2018_Dec2018_88pages_20190624.csv')
f9 = pd.read_csv('/Users/Dimitris/Desktop/headlines_Jan2018_Dec2018_88to200pages_20190624.csv')
f10 = pd.read_csv('/Users/Dimitris/Desktop/headlines_Jan2010_Dec2012_200pages_20190624.csv')

In [63]:
frames = [f1, f2, f3, f4, f5, f6, f7, f8, f9, f10]
result = pd.concat(frames)

In [64]:
result = result[['Timestamp', 'Metadata', 'Headline', 'URL', 'ShortDesc']]
result.head()

,Timestamp,Metadata,Headline,URL,ShortDesc
0,2018-01-01T04:16:04+00:00,NaN,"10 US Citizens, 2 Locals Killed in Costa Rica...",https://www.bloomberg.com/news/articles/2017-1...,"shock and disbelief right now,"" Bruce Steinbe..."
1,2018-03-27T17:31:41+00:00,politics,Mark Zuckerberg Is Expected to Testify Before...,https://www.bloomberg.com/politics/articles/20...,amid signs that Facebook has failed to prote...
2,2018-03-28T11:10:15+00:00,technology,Facebook Updates Privacy Tools for Better Dat...,https://www.bloomberg.com/news/articles/2018-0...,Facebook Inc. said it will make it more strai...
3,2018-04-11T11:11:24+00:00,NaN,Facebook's Zuckerberg Before Congress Highlig...,https://www.bloomberg.com/news/videos/2018-04-...,...
4,2018-04-26T15:08:15+00:00,NaN,Jaguars Owner Shahid Khan Makes Offer to Buy ...,https://www.bloomberg.com/news/articles/2018-0...,"scheduling future NFL games in London."" ___ R..."

In [65]:
result.dtypes

Timestamp    object
Metadata     object
Headline     object
URL          object
ShortDesc    object
dtype: object

In [66]:
result['Timestamp'] = pd.to_datetime(result['Timestamp'])
result.head()

,Timestamp,Metadata,Headline,URL,ShortDesc
0,2018-01-01 04:16:04+00:00,NaN,"10 US Citizens, 2 Locals Killed in Costa Rica...",https://www.bloomberg.com/news/articles/2017-1...,"shock and disbelief right now,"" Bruce Steinbe..."
1,2018-03-27 17:31:41+00:00,politics,Mark Zuckerberg Is Expected to Testify Before...,https://www.bloomberg.com/politics/articles/20...,amid signs that Facebook has failed to prote...
2,2018-03-28 11:10:15+00:00,technology,Facebook Updates Privacy Tools for Better Dat...,https://www.bloomberg.com/news/articles/2018-0...,Facebook Inc. said it will make it more strai...
3,2018-04-11 11:11:24+00:00,NaN,Facebook's Zuckerberg Before Congress Highlig...,https://www.bloomberg.com/news/videos/2018-04-...,...
4,2018-04-26 15:08:15+00:00,NaN,Jaguars Owner Shahid Khan Makes Offer to Buy ...,https://www.bloomberg.com/news/articles/2018-0...,"scheduling future NFL games in London."" ___ R..."

In [67]:
result = result.where((pd.notnull(result)), None)
result.head()

,Timestamp,Metadata,Headline,URL,ShortDesc
0,2018-01-01 04:16:04+00:00,None,"10 US Citizens, 2 Locals Killed in Costa Rica...",https://www.bloomberg.com/news/articles/2017-1...,"shock and disbelief right now,"" Bruce Steinbe..."
1,2018-03-27 17:31:41+00:00,politics,Mark Zuckerberg Is Expected to Testify Before...,https://www.bloomberg.com/politics/articles/20...,amid signs that Facebook has failed to prote...
2,2018-03-28 11:10:15+00:00,technology,Facebook Updates Privacy Tools for Better Dat...,https://www.bloomberg.com/news/articles/2018-0...,Facebook Inc. said it will make it more strai...
3,2018-04-11 11:11:24+00:00,None,Facebook's Zuckerberg Before Congress Highlig...,https://www.bloomberg.com/news/videos/2018-04-...,...
4,2018-04-26 15:08:15+00:00,None,Jaguars Owner Shahid Khan Makes Offer to Buy ...,https://www.bloomberg.com/news/articles/2018-0...,"scheduling future NFL games in London."" ___ R..."

In [68]:
result['Metadata'] = result['Metadata'].str.strip()
result['Headline'] = result['Headline'].str.strip()
result['URL'] = result['URL'].str.strip()
result['ShortDesc'] = result['ShortDesc'].str.strip()
result.head()

,Timestamp,Metadata,Headline,URL,ShortDesc
0,2018-01-01 04:16:04+00:00,None,"10 US Citizens, 2 Locals Killed in Costa Rica ...",https://www.bloomberg.com/news/articles/2017-1...,"shock and disbelief right now,"" Bruce Steinber..."
1,2018-03-27 17:31:41+00:00,politics,Mark Zuckerberg Is Expected to Testify Before ...,https://www.bloomberg.com/politics/articles/20...,amid signs that Facebook has failed to protect...
2,2018-03-28 11:10:15+00:00,technology,Facebook Updates Privacy Tools for Better Data...,https://www.bloomberg.com/news/articles/2018-0...,Facebook Inc. said it will make it more straig...
3,2018-04-11 11:11:24+00:00,None,Facebook's Zuckerberg Before Congress Highlights,https://www.bloomberg.com/news/videos/2018-04-...,"""It was my mistake and I'm sorry,"" says Facebo..."
4,2018-04-26 15:08:15+00:00,None,Jaguars Owner Shahid Khan Makes Offer to Buy W...,https://www.bloomberg.com/news/articles/2018-0...,"scheduling future NFL games in London."" ___ Ro..."

In [69]:
result.shape

(9130, 5)

In [70]:
duplicateRowsDF = result[result.duplicated()]
 
print("Duplicate Rows except first occurrence based on all columns are : ", len(duplicateRowsDF.index))
#print(duplicateRowsDF)

Duplicate Rows except first occurrence based on all columns are :  3103

In [71]:
result = result[result.duplicated() == False]
result.shape

(6027, 5)

In [1]:
result.head()

NameError: name 'result' is not defined

In [73]:
result = result.sort_values(by='Timestamp')
result = result.reset_index(drop=True)
result.head()

,Timestamp,Metadata,Headline,URL,ShortDesc
0,2010-01-04 18:28:40+00:00,None,Friendly Competition,https://www.bloomberg.com/news/articles/2010-0...,"where I found out that my section, the Highlan..."
1,2010-01-05 05:00:00+00:00,None,The Ritualization of Creation--The Role of Rit...,https://www.bloomberg.com/news/articles/2010-0...,medium). Ditto for social media. ...
2,2010-01-05 05:00:33+00:00,None,Silicon Valley 'Bloodbath' Leaves Entire Offic...,https://www.bloomberg.com/news/articles/2010-0...,Some technology companies are taking the oppor...
3,2010-01-05 17:41:00+00:00,None,An Amish Entrepreneur's Old-Fashioned Approach,https://www.bloomberg.com/news/articles/2010-0...,the Internet. No e-mail newsletters or Web sit...
4,2010-01-07 15:27:08+00:00,technology,"Google, Yahoo! May Face New Online Advertising...",https://www.bloomberg.com/news/articles/2010-0...,France should start taxing Internet advertisin...

In [135]:
result.to_csv('/Users/Dimitris/Desktop/all_headlines_Dec2017_to_July2018.csv', index=False)

In [138]:
result.shape

(810, 5)

In [137]:
perim_results = result[(result['Timestamp'] >= '2018-01-01') & (result['Timestamp'] < '2018-06-30')]
perim_results = perim_results.reset_index(drop=True)
perim_results.head()

,Timestamp,Metadata,Headline,URL,ShortDesc
0,2018-01-01 04:16:04+00:00,None,"10 US Citizens, 2 Locals Killed in Costa Rica ...",https://www.bloomberg.com/news/articles/2017-1...,"shock and disbelief right now,"" Bruce Steinber..."
1,2018-01-01 16:02:27+00:00,politics,Death Toll in Iran Protests Climbs as Rouhani ...,https://www.bloomberg.com/politics/articles/20...,"protesting channels.” The government, which ha..."
2,2018-01-03 04:05:05+00:00,politics,Macron and Uber Era Threaten Role of Once-Powe...,https://www.bloomberg.com/politics/articles/20...,"talk, the union has been ill-equipped to deal ..."
3,2018-01-03 11:00:14+00:00,view,Americans Should Have More Control Over Their ...,https://www.bloomberg.com/view/articles/2018-0...,-- and exploit it for commercial purposes. It ...
4,2018-01-03 11:23:51+00:00,politics,Iran's Poor Turn Against Its Ruling Clerics,https://www.bloomberg.com/politics/articles/20...,morning? Sign up for the Balance of Power news...

In [139]:
perim_results.shape

(665, 5)

In [140]:
perim_results.to_csv('/Users/Dimitris/Desktop/all_665_headlines_Jan2018_to_June2018.csv', index=False)

In [1]:
import pandas as pd
news = pd.read_csv('/Users/Dimitris/PycharmProjects/stock_deep_learning/news.csv')

In [2]:
news.head(10)

         Date                                           Headline
0  2008-06-08  b'Albino Killings in Tanzania. At least 19 alb...
1  2008-06-08  b'Polar bear swims 200 miles, is shot dead upo...
2  2008-06-08  b'News is a contraband item in Pakistan now, a...
3  2008-06-08  b'Albinos, Long Shunned, Face Threat in Tanzan...
4  2008-06-08  b'Town in Britain Plans to Start its Own Curre...
5  2008-06-08       b'BBC reporter among 16 dead in Afghanistan'
6  2008-06-08  b'Lebanese women still vulnerable to violence:...
7  2008-06-08  b'Police release chilling images of man left f...
8  2008-06-08  b'Chiapas: army occupies Zapatista communities...
9  2008-06-08  b"Iceland opens Europe's largest national park...

In [5]:
filename = '/Users/Dimitris/PycharmProjects/stock_deep_learning/dataset/kaggle/RedditNews.csv'
rd = pd.read_csv(filename)
rd.head()

         Date                                               News
0  2016-07-01  A 117-year-old woman in Mexico City finally re...
1  2016-07-01   IMF chief backs Athens as permanent Olympic host
2  2016-07-01  The president of France says if Brexit won, so...
3  2016-07-01  British Man Who Must Give Police 24 Hours' Not...
4  2016-07-01  100+ Nobel laureates urge Greenpeace to stop o...

In [41]:
rd['News'] = rd['News'].str.replace(r'^b"|"$', '', regex=True)
rd['News'] = rd['News'].str.replace(r'^b''|\'$', '', regex=True)
rd['News'] = rd['News'].str.replace(r'^|"$', '', regex=True)
rd['News'] = rd['News'].str.replace(r'^\'|\'$', '', regex=True)
rd['News'] = rd['News'].str.strip()
rd['News'] = rd['News'].str.strip('\t')
rd['News']

0        A 117-year-old woman in Mexico City finally re...
1         IMF chief backs Athens as permanent Olympic host
2        The president of France says if Brexit won, so...
3        British Man Who Must Give Police 24 Hours' Not...
4        100+ Nobel laureates urge Greenpeace to stop o...
5        Brazil: Huge spike in number of police killing...
6        Austria's highest court annuls presidential el...
7        Facebook wins privacy case, can track any Belg...
8        Switzerland denies Muslim girls citizenship af...
9        China kills millions of innocent meditators fo...
10       France Cracks Down on Factory Farms - A viral ...
11       Abbas PLO Faction Calls Killer of 13-Year-Old ...
12       Taiwanese warship accidentally fires missile t...
13       Iran celebrates American Human Rights Week, mo...
14       U.N. panel moves to curb bias against L.G.B.T....
15       The United States has placed Myanmar, Uzbekist...
16       S&amp;P revises European Union credit rating t...
17       India gets $1 billion loan from World Bank for...
18       U.S. sailors detained by Iran spoke too much u...
19       Mass fish kill in Vietnam solved as Taiwan ste...
20       Philippines president Rodrigo Duterte urges pe...
21       Spain arrests three Pakistanis accused of prom...
22       Venezuela, where anger over food shortages is ...
23       A Hindu temple worker has been killed by three...
24       Ozone layer hole seems to be healing - US &amp...
25       Jamaica proposes marijuana dispensers for tour...
26       Stephen Hawking says pollution and 'stupidity'...
27       Boris Johnson says he will not run for Tory pa...
28       Six gay men in Ivory Coast were abused and for...
29       Switzerland denies citizenship to Muslim immig...
                               ...
73578    Future of the United States of Europe in the H...
73579    Military coup' in Zimbabwe as Mugabe is forced...
73580    Rising Oil Prices Spark Strikes in Spain and a...
73581    Chvez to FARC: Asks to end armed strugle, "The...
73582            Fliers in for pain as airlines pack it in
73583    Nim Chimpsky: The tragedy of the chimp who tho...
73584    Canada: Beware slippery slope' to censorship, ...
73585    EU Vice-President Luisa Morgantini and the Iri...
73586    Israeli minister: Israel will attack Iran if i...
73587    Albino Killings in Tanzania. At least 19 albin...
73588    Chiapas: army occupies Zapatista communities i...
73589    Polar bear swims 200 miles, is shot dead upon ...
73590    News is a contraband item in Pakistan now, and...
73591    Albinos, Long Shunned, Face Threat in Tanzania...
73592      Town in Britain Plans to Start its Own Currency
73593            BBC reporter among 16 dead in Afghanistan
73594    Lebanese women still vulnerable to violence: e...
73595    Police release chilling images of man left for...
73596    Iceland opens Europe's largest national park. ...
73597    Citizens fighting Blackwater Potrero. Was the ...
73598    S. Korean protesters, police clash in beef ral...
73599    Oil reserves 'will last decades' - a BBC Scotl...
73600    Cameras designed to detect terrorist facial ex...
73601    Israeli peace activists protest 41 years of oc...
73602    A 5.1 earthquake hits China's Southern Qinghai...
73603    Man goes berzerk in Akihabara and stabs everyo...
73604    Threat of world AIDS pandemic among heterosexu...
73605    Angst in Ankara: Turkey Steers into a Dangerou...
73606    UK: Identity cards 'could be used to spy on pe...
73607    Marriage, they said, was reduced to the status...
Name: News, Length: 73608, dtype: object

In [32]:
import re

#data = []
#with open(filename, 'r') as f:
#    for row in f:
#        l = []
#        for item in row.split(',', 1):
#            i = item
#            i = re.sub(r'^"|"$', '', i)
#            i = re.sub(r'^b"|"$', '', i)
#            i = re.sub(r'^b\'|\'$', '', i)
#            i = re.sub(r'^"|"$', '', i)
#            l.append(i)
#        data.append(l)
            #print(re.sub(r'^"|"$', '', item))
        #data.append([re.sub(r'^"|"$', '', item).strip() for item in row.split(',', 1)])
#df = pd.DataFrame(data[1:], columns= ['Date', 'Headline'])
#df['Date'] = pd.to_datetime(df['Date'].str.strip(), utc=True).dt.date
#df['Headline'] = df['Headline'].str.strip().strip("'").strip("\"").strip()
#df = df[df.duplicated() == False]
#df.columns = ['Date', 'Headline']

data = []
with open(filename, 'r') as f:
    for row in f:
        lst = []
        for item in row.split(',', 1):
            i = item
            i = re.sub(r'^"|"$', '', i)
            i = re.sub(r'^b"|"$', '', i)
            i = re.sub(r'^b\'|\'$', '', i)
            i = re.sub(r'^"|"$', '', i)
            lst.append(i)
        data.append(lst)
        
df = pd.DataFrame(data[1:], columns= ['Date', 'Headline'])

In [33]:
df

             Date                                           Headline
0      2016-07-01  A 117-year-old woman in Mexico City finally re...
1      2016-07-01  IMF chief backs Athens as permanent Olympic ho...
2      2016-07-01  The president of France says if Brexit won, so...
3      2016-07-01  British Man Who Must Give Police 24 Hours' Not...
4      2016-07-01  100+ Nobel laureates urge Greenpeace to stop o...
5      2016-07-01  Brazil: Huge spike in number of police killing...
6      2016-07-01  Austria's highest court annuls presidential el...
7      2016-07-01  Facebook wins privacy case, can track any Belg...
8      2016-07-01  Switzerland denies Muslim girls citizenship af...
9      2016-07-01  China kills millions of innocent meditators fo...
10     2016-07-01  France Cracks Down on Factory Farms - A viral ...
11     2016-07-01  Abbas PLO Faction Calls Killer of 13-Year-Old ...
12     2016-07-01  Taiwanese warship accidentally fires missile t...
13     2016-07-01  Iran celebrates American Human Rights Week, mo...
14     2016-07-01  U.N. panel moves to curb bias against L.G.B.T....
15     2016-07-01  The United States has placed Myanmar, Uzbekist...
16     2016-07-01  S&amp;P revises European Union credit rating t...
17     2016-07-01  India gets $1 billion loan from World Bank for...
18     2016-07-01  U.S. sailors detained by Iran spoke too much u...
19     2016-07-01  Mass fish kill in Vietnam solved as Taiwan ste...
20     2016-07-01  Philippines president Rodrigo Duterte urges pe...
21     2016-07-01  Spain arrests three Pakistanis accused of prom...
22     2016-07-01  Venezuela, where anger over food shortages is ...
23     2016-07-01  A Hindu temple worker has been killed by three...
24     2016-07-01  Ozone layer hole seems to be healing - US &amp...
25     2016-06-30  Jamaica proposes marijuana dispensers for tour...
26     2016-06-30  Stephen Hawking says pollution and 'stupidity'...
27     2016-06-30  Boris Johnson says he will not run for Tory pa...
28     2016-06-30  Six gay men in Ivory Coast were abused and for...
29     2016-06-30  Switzerland denies citizenship to Muslim immig...
...           ...                                                ...
76570  2008-06-09  Future of the United States of Europe in the H...
76571  2008-06-09  'Military coup' in Zimbabwe as Mugabe is force...
76572  2008-06-09  Rising Oil Prices Spark Strikes in Spain and a...
76573  2008-06-09  Chvez to FARC: Asks to end armed strugle, ""Th...
76574  2008-06-09        Fliers in for pain as airlines pack it in\n
76575  2008-06-08  Nim Chimpsky: The tragedy of the chimp who tho...
76576  2008-06-08  Canada: Beware slippery slope' to censorship, ...
76577  2008-06-08  EU Vice-President Luisa Morgantini and the Iri...
76578  2008-06-08  Israeli minister: Israel will attack Iran if i...
76579  2008-06-08  Albino Killings in Tanzania. At least 19 albin...
76580  2008-06-08  Chiapas: army occupies Zapatista communities i...
76581  2008-06-08  Polar bear swims 200 miles, is shot dead upon ...
76582  2008-06-08  News is a contraband item in Pakistan now, and...
76583  2008-06-08  Albinos, Long Shunned, Face Threat in Tanzania...
76584  2008-06-08  Town in Britain Plans to Start its Own Currency\n
76585  2008-06-08        BBC reporter among 16 dead in Afghanistan\n
76586  2008-06-08  Lebanese women still vulnerable to violence: e...
76587  2008-06-08  Police release chilling images of man left for...
76588  2008-06-08  Iceland opens Europe's largest national park. ...
76589  2008-06-08  Citizens fighting Blackwater Potrero. Was the ...
76590  2008-06-08  S. Korean protesters, police clash in beef ral...
76591  2008-06-08  Oil reserves 'will last decades' - a BBC Scotl...
76592  2008-06-08  Cameras designed to detect terrorist facial ex...
76593  2008-06-08  Israeli peace activists protest 41 years of oc...
76594  2008-06-08  A 5.1 earthquake hits China's Southern Qinghai...
76595  2008-06-08  Man goes berzerk in Akihabara and stabs everyo...
76596  2008-06-08  Threat of world AIDS pandemic among heterosexu...
76597  2008-06-08  Angst in Ankara: Turkey Steers into a Dangerou...
76598  2008-06-08  UK: Identity cards 'could be used to spy on pe...
76599  2008-06-08  Marriage, they said, was reduced to the status...

[76600 rows x 2 columns]

In [134]:
# Iteration between Dates reference function

from datetime import timedelta, date

def daterange(start_date, end_date):
    for n in range(int ((end_date - start_date).days)):
        yield start_date + timedelta(n)

        
start_date = date(2018, 1, 1)
end_date = date(2018, 6, 30)

#for single_date in daterange(start_date, end_date):
#    print(single_date.strftime("%Y-%m-%d"))

In [4]:
import pandas as pd
stock_df = pd.read_csv("/Users/Dimitris/PycharmProjects/stocks_predictions_deep_learning/dataset/final/FB.csv")

In [6]:
stock_df.head()

,Date,High,Low,Open,Close,Volume,Adj Close
0,2012-05-18,45.000000,38.000000,42.049999,38.230000,573576400,38.230000
1,2012-05-21,36.660000,33.000000,36.529999,34.029999,168192700,34.029999
2,2012-05-22,33.590000,30.940001,32.610001,31.000000,101786600,31.000000
3,2012-05-23,32.500000,31.360001,31.370001,32.000000,73600000,32.000000
4,2012-05-24,33.209999,31.770000,32.950001,33.029999,50237200,33.029999

In [8]:
stocks=stock_df
dj = stocks.set_index('Date').diff(periods=1)
dj['Date'] = dj.index
dj = dj.reset_index(drop=True)
dj = dj.drop(['High', 'Low', 'Close', 'Volume', 'Adj Close'], 1)
dj = dj[dj.Open.notnull()]
dj.head()

       Open        Date
1 -5.520000  2012-05-21
2 -3.919998  2012-05-22
3 -1.240000  2012-05-23
4  1.580000  2012-05-24
5 -0.049999  2012-05-25

In [11]:
stocks=stock_df
dj = stocks
dj = dj.drop(['High', 'Low', 'Open', 'Volume', 'Adj Close'], 1)
dj = dj[dj.Close.notnull()]
dj.head()

         Date      Close
0  2012-05-18  38.230000
1  2012-05-21  34.029999
2  2012-05-22  31.000000
3  2012-05-23  32.000000
4  2012-05-24  33.029999